version: '3.9'

# Development-optimized compose file
# Usage: docker-compose -f infra/compose.dev.yaml up

services:
  db:
    image: postgres:16-alpine
    container_name: taskboard-db-dev
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - taskboard-network

  redis:
    image: redis:7-alpine
    container_name: taskboard-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - taskboard-network

volumes:
  postgres_data_dev:
  redis_data_dev:

networks:
  taskboard-network:
    driver: bridge

